version: '3'

vars:
  DATABASE_URL: "postgres://postgres:mysecretpassword@localhost:5432/easy_football_tycoon?sslmode=disable"
  MIGRATION_DIR: "./migrations"
  migrate: migrate

tasks:
  migrate-up:
    desc: "Run migrations up"
    cmds:
      - "{{.migrate}} -path {{.MIGRATION_DIR}} -database {{.DATABASE_URL}} up"

  migrate-down:
    desc: "Run migrations down"
    cmds:
      - "{{.migrate}} -path {{.MIGRATION_DIR}} -database {{.DATABASE_URL}} down"

  migrate-down-all:
    desc: "Run all migrations down"
    cmds:
      - "{{.migrate}} -path {{.MIGRATION_DIR}} -database {{.DATABASE_URL}} down all"

  seed-db:
    desc: "Seed the database with initial data"
    cmds:
      - psql "{{.DATABASE_URL}}" -f "{{.MIGRATION_DIR}}/seed_data.sql"
